# -*- coding: utf-8 -*-
"""DS Day - 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhUpX0Yaf69iNZ9-uj43-Aq8UepMDwb9
"""

import numpy as np

arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

print("Array is of type: ", type(arr))


print("No. of dimensions: ", arr.ndim)

print("Shape of array: ", arr.shape)

print("Size of array: ", arr.size)

print("Array stores elements of type: ", arr.dtype)

import numpy as np


arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)


arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

import numpy as np

arr = np.array([2, 4, 6, 8, 10])

c = arr.copy()

print("id of arr", id(arr))
print("id of c", id(c))


arr[0] = 12

print("original array- ", arr)
print("copy- ", c)

def sum(array):


	sum = 0

	for i in array:

		sum += i


	return sum


testArray = [1, 3, 34, 92, 29, 48, 20.3]


print('The sum of your numbers is ' + str(sum(testArray)))

import numpy as np

a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)

newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


newarr = arr.reshape(2, 3, 2)
print(newarr)

import numpy


x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])


print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))


print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))

import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

import pandas as pd

print(pd.__version__)

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)


print(myvar[0])

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)

print(df)


print(df.loc[0])

print(df.loc[[0, 1]])

import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

"""# New section

# New section
"""

import pandas as pd

df = pd.read_csv('data.csv')

print(df)

import pandas as pd

print(pd.options.display.max_rows)

import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('data.csv')

print(df)

print(pd.options.display.max_rows)

JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

import pandas as pd


df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)


df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)

display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

import pandas as pd

df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)


df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)


display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

import pandas as pd


df = pd.read_csv("nba.csv")


print(df.head())

gk = df.groupby('Team')

gk.first()

gk.get_group('Boston Celtics')

j = 1

while(j<= 5):
	print(j)
	j = j + 1